ALTER TABLE IF EXISTS PUBLIC."All_Media" ADD PRIMARY KEY ("Title");


ALTER TABLE IF EXISTS PUBLIC."Anime" ADD PRIMARY KEY ("index");


ALTER TABLE IF EXISTS PUBLIC."Netflix" ADD PRIMARY KEY ("index");


ALTER TABLE IF EXISTS PUBLIC."Youtube/US" ADD PRIMARY KEY ("index");